title: Reboot Dialog for Windows
description: Will run silently in background and show a popup dialog when reboot is needed with snooze options. Support Windows 7+

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-49827113-2
