title: Reboot Dialog for Windows
description: Will run silently in background and show a popup dialog when reboot is needed with snooze options. Support Windows 7+

permalink: pretty

twitter:
  username: rydin_fredrik

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

show_downloads: true
theme: jekyll-theme-slate
google_analytics: UA-49827113-2

# Site Author
author:
  name: Fredrik Rydin
  links:
    - title: Twitter
      url: https://twitter.com/rydin_fredrik
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/Fredrik81
      icon: fab fa-github-square

# Footer Links
footer_links:
  links:
    - title: Twitter
      url: https://twitter.com/rydin_fredrik
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/Fredrik81
      icon: fab fa-github-square
